// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// authority_name
std::string authority_name(std::string x);
RcppExport SEXP _pegax_authority_name(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(authority_name(x));
    return rcpp_result_gen;
END_RCPP
}
// authority_year
std::string authority_year(std::string x);
RcppExport SEXP _pegax_authority_year(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(authority_year(x));
    return rcpp_result_gen;
END_RCPP
}
// name_subsp
std::string name_subsp(std::string x);
RcppExport SEXP _pegax_name_subsp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(name_subsp(x));
    return rcpp_result_gen;
END_RCPP
}
// hello_world
std::string hello_world(std::string x);
RcppExport SEXP _pegax_hello_world(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hello_world(x));
    return rcpp_result_gen;
END_RCPP
}
