// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// peg_sum
NumericVector peg_sum(CharacterVector x);
RcppExport SEXP pegax_peg_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(peg_sum(x));
    return rcpp_result_gen;
END_RCPP
}
// hell_world
std::string hell_world(std::string x);
RcppExport SEXP pegax_hell_world(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hell_world(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"pegax_peg_sum", (DL_FUNC) &pegax_peg_sum, 1},
    {"pegax_hell_world", (DL_FUNC) &pegax_hell_world, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_pegax(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
