# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

authority_name <- function(x) {
    .Call('_pegax_authority_name', PACKAGE = 'pegax', x)
}

authority_year <- function(x) {
    .Call('_pegax_authority_year', PACKAGE = 'pegax', x)
}

replace_all_symbols <- function(x) {
    .Call('_pegax_replace_all_symbols', PACKAGE = 'pegax', x)
}

replace_specific_symbols <- function(x) {
    .Call('_pegax_replace_specific_symbols', PACKAGE = 'pegax', x)
}

rank_names <- function(x) {
    .Call('_pegax_rank_names', PACKAGE = 'pegax', x)
}

scrub_names <- function(x) {
    .Call('_pegax_scrub_names', PACKAGE = 'pegax', x)
}

