# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

authority_year <- function(x) {
    .Call('pegax_authority_year', PACKAGE = 'pegax', x)
}

authority_name <- function(x) {
    .Call('pegax_authority_name', PACKAGE = 'pegax', x)
}

peg_sum <- function(x) {
    .Call('pegax_peg_sum', PACKAGE = 'pegax', x)
}

hello_world <- function(x) {
    .Call('pegax_hello_world', PACKAGE = 'pegax', x)
}

